[project]
name = "guardrails-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "azure-ai-contentsafety>=1.0.0",
    "azure-core>=1.39.0",
    "presidio-analyzer>=2.2.0",
    "presidio-anonymizer>=2.2.0",
    "python-dotenv>=1.2.2",
    "spacy>=3.4.0",
]
